### 新建一篇文章
POST http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

id=4&avatar=&tag=1&tag=2&title=test1&text=faoifjfdlfdfjaldhfuakfheufheuiofhkajhfksdfhakfhadkfhndkfhasdf

### 根据 ID 查找文章
GET http://localhost:24540/blog/search
Content-Type: application/x-www-form-urlencoded

id=1

### 修改文章内容
PUT http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

id=4&tag=1&avatar=&title=test3&text=11

### 删除一篇文章
DELETE http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

id=2


### 查找所有文章
GET http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

### 查找固定条数文章
GET http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

limit=4

#################################

### 新建一个项目

POST http://localhost:24540/work
Content-Type: application/x-www-form-urlencoded

id=4&avatar=&title=test1&tag=1&tag=2&content=yhsiuhfiaufhisduafhaidsfhuiadsfhidsa&preview=github&source=github&lastupdate=153334444333&version=1.0&status=1

### 查找所有项目
GET http://localhost:24540/work
Content-Type: application/x-www-form-urlencoded

### 查找指定条数项目
GET http://localhost:24540/work
Content-Type: application/x-www-form-urlencoded

limit=2

### 修改项目内容
PUT http://localhost:24540/work
Content-Type: application/x-www-form-urlencoded

id=4&avatar=&title=test4&tag=4&content=1&status=1
