### 新建一篇文章
POST http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

id=4&avatar=&tag=1&tag=2&title=test1&text=faoifjfdlfdfjaldhfuakfheufheuiofhkajhfksdfhakfhadkfhndkfhasdf

### 根据 ID 查找文章
GET http://localhost:24540/blog/search
Content-Type: application/x-www-form-urlencoded

id=1

### 修改文章内容
PUT http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

id=4&tag=1&avatar=&title=test3&text=11

### 删除一篇文章
GET http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

id=5f89e68f6a73732732f8cbd6


### 查找所有文章
GET http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

### 查找固定条数文章
GET http://localhost:24540/blog
Content-Type: application/x-www-form-urlencoded

limit=4